### ISSUE TITLE
Start gets activated before conversation when cutscene not skipped

### ISSUE THREAD

**Issue by mitchell-merry** [PoPRuns/LiveSplit.POPTLC#1]
And if you reset before the conversation it'll activate again.

```
inputMode: 0 -> 3 
inputMode: 3 -> 0 
inputMode: 0 -> 2 
inputMode: 2 -> 3 
inputMode: 3 -> 0 
```

This is not actually an issue since nobody will actually wait the whole conversation out probably.

**Comment by GMPranav** [comment]
This issue is no longer a problem with the new start logic I think
