### ISSUE TITLE
[Feature] More autosplit options for Abilities, Bosses, and More for cases where main story flags might be skipped or extra is being done.

### ISSUE THREAD

**Issue by BobbyGBs** [PoPRuns/LiveSplit.POPTLC#21]
### Description

Known spots where it doesn't autosplit for any% which it would be nice to have (in order) Main Wishlist
- General Uvishka
- The Haven Discovery
- Bow
- Tower of Silence Discovery
- Claw
- Upper City - West Discovery
- Twin shield girl fight at the top of the map
- King Darius
- Royal Corridors Discovery
- Vahram Time and Space final input. (doesn't split without the quest)

--Extra stuff
Abilities:
- Bow of Menolias
- Chakram
- Teleport (same as Menolias boss)
- Rush of the Simurgh
- Shadow of the Simurgh
- Dimensional Claw
- Clairvoyance
- Gravity Wings
- Fabric of Time (same as vahram 2 might not be needed)
- Holy Scholarship Key

Bosses:
- General Uvishka
- Undead Prisoner
- Erlik
- Vahram 1 (abducted prince doesn't split if the fight with the guards is skipped iirc)
- Vahram 2
- Alt Sargons (idk how many there are I am not going to list them all)
- Kiana the Forest Queen
- Azdaha
- Giant Crab
- Undead Erlik
- Orod
- Menolias
- King Darius
- Vahram Time and Space

Potential other things
- Constellation spots (since azdaha skip is known and menolias skip is possible)
- Side Quests
- Discovery locations--

### Link to a video with timestamps.

https://youtu.be/6ln17R1S_Z0?si=6QTblf7O8EtPmwIi
Wishlist splits would be at
3:20 Uvishka
6:59 Haven
10:20 Bow
12:37 Silence
17:55 Claw
21:09 Upper West
23:09 Twins
28:16 Darius
30:08 Royal
35:24 Vahram
For the ones that are in the video I am manually splitting but it would be nice if I didnt have to.

### Are you willing to help test?

- [X] I can help test the feature.

**Comment by BobbyGBs** [comment]
Best way to reach out to me to help with testing would be though my discord @b.g.b. I am easily findable in the PoP discord.

**Comment by mitchell-merry** [comment]
Please split this into multiple feature requests. One for bosses, one for abilities, etc - this is far too many for one


I'll have a preliminary look into this at some point, though

**Comment by BobbyGBs** [comment]
Sorry I am getting back to you so late. Just think of this post as the main Wishlist of stuff for any% and ignore everything else. I tried to be too thorough. 
I or someone else can make more requests for the other stuff when need be.
